services:
  backend:
    build:
      context: /Users/ankitladva/Downloads/experiments-al-deployment_Injection
      dockerfile: Dockerfile.backend
    container_name: kyc-backend
    ports:
      - "8000:8000"
    volumes:
      - data_volume:/app/data
    env_file:
      - /Users/ankitladva/Downloads/experiments-al-deployment_Injection/kyc-backend.env
    environment:
      - API_KEY=${API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: /Users/ankitladva/Downloads/experiments-al-deployment_Injection
      dockerfile: face-verification-ui/Dockerfile.frontend
      args:
        # These are injected into the Vite build and must be set in your shell or env file
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_API_KEY: ${VITE_API_KEY}
    container_name: kyc-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data_volume: 