services:
  backend:
    build:
      context: /Users/ankitladva/Downloads/experiments-al-deployment_Injection
      dockerfile: Dockerfile.backend
    container_name: kyc-backend
    ports:
      - "8000:8000"
    volumes:
      - data_volume:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: /Users/ankitladva/Downloads/experiments-al-deployment_Injection
      dockerfile: face-verification-ui/Dockerfile.frontend
    container_name: kyc-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data_volume: 